name: Integrational tests
on:
  push:
    paths-ignore:
      - 'doc/**'

jobs:
  run-tests:
    name: Run Intergrational tests using Kind
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.7.0"

      - name: Deploy to Kuberenetes
        run: |-
          kubectl apply -f rbac.yaml
          kubectl apply -f config.yaml
          kubectl apply -f hazelcast.yaml

      - name: Test for successful Deployment
        run: |-
          kubectl wait --for=condition=ready pod/hazelcast-0 --timeout=120s
          kubectl wait --for=condition=ready pod/hazelcast-1 --timeout=120s
          kubectl wait --for=condition=ready pod/hazelcast-2 --timeout=120s

